<div class="main-container">

    <!-- =========== START: ANALYTICS DASHBOARD =========== -->
    <div class="analytics-dashboard">
        <div class="dashboard-header">
            <h2><i class="fas fa-filter"></i> Employee Filtering & Management</h2>
            <p>Use the filters below to refine the employee roster and update the chart.</p>
        </div>
        
        <div class="dashboard-filter-bar">
            <div class="filter-controls-wrapper">
                 <div class="filter-control-group">
                    <label>Filters</label>
                    <div>
                         <button id="employee-filter-btn" class="btn"><i class="fas fa-filter"></i> Location Filter</button>
                         <button id="metrics-filter-btn" class="btn"><i class="fas fa-sliders-h"></i> Metrics Filter</button>
                         <div class="custom-select-wrapper" style="display: inline-block;">
                            <button id="status-filter-btn" class="btn"><i class="fas fa-flag"></i> Status</button>
                            <div id="status-filter-dropdown" class="custom-select-options" style="width: 200px; right: 0; left: auto;">
                                <input type="text" class="custom-select-search" placeholder="Search...">
                                <ul></ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="filter-control-group">
                    <label>Detailed Filters</label>
                    <!--<div style="display: flex; gap: 1rem; align-items: center;">-->
                    <div>
                        <div id="employee-select-wrapper" class="custom-select-wrapper"></div>
                        <div id="trainer-level-select-wrapper" class="custom-select-wrapper"></div>
                        <div id="certification-select-wrapper" class="custom-select-wrapper"></div>
                    </div>
                </div>
                <div class="filter-control-group">
                    <label>General Actions</label>
                    <div>
                        <button id="refresh-table-btn" class="btn" title="Refresh Table & Clear Filters"><i class="fas fa-sync-alt"></i> Refresh</button>
                    </div>
                </div>
            </div>
            <div id="filter-tags-container" class="filter-tags-container"></div>
        </div>
        
        <!-- =========== START: DYNAMIC 3D CHART =========== -->
        <div class="dynamic-chart-wrapper">
             <div id="chart-container" class="chart-container">
                <div class="chart-header">
                    <h2 class="chart-title" id="chart-main-title">Trainer Performance & Sessions</h2>
                    <div class="right-controls">
                        <div class="chart-actions">
                            <button id="download-chart-png" class="btn"><i class="fas fa-image"></i> PNG</button>
                            <button id="download-chart-pdf" class="btn"><i class="fas fa-file-pdf"></i> PDF</button>
                        </div>
                        <div id="chart-granularity-selector" class="chart-granularity-selector">
                            <button data-granularity="daily">Daily</button>
                            <button data-granularity="weekly">Weekly</button>
                            <button data-granularity="monthly" class="active">Monthly</button>
                            <button data-granularity="yearly">Yearly</button>
                        </div>
                    </div>
                </div>

                <div class="chart-area">
                    <div class="y-axis y-axis-left" id="chart-yaxis"></div>
                    <div class="y-axis y-axis-avg" id="line-chart-yaxis-avg"></div>
                    
                    <div class="plot-area">
                        <canvas id="line-chart-canvas"></canvas>
                        <div id="chart-grid-lines" class="grid-lines"></div>
                        <div id="chart-bar-totals-container" class="bar-totals-container"></div>
                        <div id="chart-bars-container" class="bars-container"></div>
                    </div>
                    
                    <div class="y-axis y-axis-right" id="line-chart-yaxis-right"></div>
                    
                    <div class="x-axis">
                        <div id="chart-xaxis-labels" class="x-axis-labels"></div>
                    </div>
                </div>

                <div class="legend" id="chart-legend">
                    <!-- Legend will be dynamically generated by JavaScript -->
                </div>
                <div id="chart-no-data-overlay" class="chart-no-data-overlay" style="display: none;">
                    <span>No data available for the selected timeline</span>
                </div>
            </div>
        </div>
         <!-- =========== END: DYNAMIC 3D CHART =========== -->

    </div>

    <div class="table-controls-section">
        <header class="table-header">
            <div class="table-title-wrapper">
                <h1>Employee Roster</h1>
            </div>
            <div class="header-controls">
                <div class="bulk-action-controls">
                    <button id="mark-active-btn" class="btn bulk-status-btn" disabled><i class="fas fa-check"></i> Mark Active</button>
                    <button id="mark-inactive-btn" class="btn bulk-status-btn" disabled><i class="fas fa-times"></i> Mark Inactive</button>
                </div>
                <button id="download-excel-btn" class="btn"><i class="fas fa-file-excel"></i> Download Excel</button>
                <div class="search-add-wrapper">
                    <div class="search-input-container">
                        <i class="fas fa-magnifying-glass"></i>
                        <input type="text" id="employee-search-input" placeholder="Search & add employees...">
                    </div>
                    <div class="search-results-container" id="search-results-container">
                        <div id="search-actions-container">
                            <div id="selected-for-addition-preview"></div>
                            <div class="actions-bar">
                                <div class="select-all-container">
                                    <input type="checkbox" id="select-all-checkbox">
                                    <label for="select-all-checkbox">Select All</label>
                                </div>
                                <button id="bulk-add-btn" class="btn" disabled>Add Selectedadssssssssss</button>
                            </div>
                        </div>
                        <ul id="search-results-list"></ul>
                    </div>
                </div>
            </div>
        </header>
    </div>


    <div class="table-wrapper">
        <table>
            <thead>
                <tr>
                    
                    <th><input type="checkbox" id="select-all-table-checkbox"></th>
                    <th>Employee Info</th>
                    <th>Role & Responsibility</th>
                    <th>Certifications</th>
                    <th>Training Metrics</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="employee-table-body"></tbody>
        </table>
    </div>
    <footer class="table-pagination-footer" id="pagination-footer"></footer>
</div>

<!-- All Modals -->
<div id="employee-filter-modal-overlay" class="filter-modal-overlay">
    <div class="filter-modal">
        <div class="filter-modal-header">
            <h2>FILTER LOCATIONS</h2>
            <button id="close-employee-filter-modal" class="close-filter-btn">×</button>
        </div>
        <div class="filter-modal-body">
            <div class="cascading-filter-container" id="cascading-filter-container"></div>
        </div>
        <div class="filter-modal-footer">
            <button id="reset-employee-filters-btn" class="btn">Reset Filters</button>
            <button id="apply-employee-filters-btn" class="btn btn-primary">Apply Filters</button>
        </div>
    </div>
</div>

<div id="metrics-filter-modal-overlay" class="filter-modal-overlay">
    <div id="metrics-filter-modal" class="filter-modal" style="max-width: 600px;">
        <div class="filter-modal-header">
            <h2>FILTER METRICS</h2>
            <button id="close-metrics-filter-modal" class="close-filter-btn">×</button>
        </div>
        <div class="filter-modal-body" id="metrics-filter-body">
            <!-- Redesigned metrics filter content will be injected here -->
        </div>
        <div class="filter-modal-footer"><button id="reset-metrics-filter-btn" class="btn">Reset Filters</button><button id="apply-metrics-filter-btn" class="btn btn-primary">Apply</button></div>
    </div>
</div>

<div id="refresh-toast" class="refresh-toast"></div>

